export const books = [
  {
    id: 1,
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    image:
      "https://www.madrasshoppe.com/207337-large_default/harry-potter-7-volume-children-s-paperback-boxed-set-the-complete-collection-set-of-7-volumes-jk-rowling.jpg",
    price: 100,
    discountPercent: 20,
    discountedPrice: 80,
    genres: ["Fantasy", "Adventure"],
    tags: ["Bestseller", "Classic"],
    rating: 4.9,
    reviews: 1250,
    stock: 15,
  },
  {
    id: 2,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    image: "https://m.media-amazon.com/images/I/71sN9fWQmeL._AC_UY218_.jpg",
    price: 120,
    discountPercent: 10,
    discountedPrice: 108,
    genres: ["Fantasy", "Adventure"],
    tags: ["Classic", "Limited Edition"],
    rating: 4.8,
    reviews: 945,
    stock: 5,
  },
  {
    id: 3,
    title: "Atomic Habits",
    author: "James Clear",
    image: "https://m.media-amazon.com/images/I/81c9b7fPrNL._AC_UY218_.jpg",
    price: 150,
    discountPercent: 15,
    discountedPrice: 127.5,
    genres: ["Self-Help", "Productivity"],
    tags: ["Trending", "Recommended"],
    rating: 4.7,
    reviews: 850,
    stock: 10,
  },
  {
    id: 4,
    title: "The Alchemist",
    author: "Paulo Coelho",
    image: "https://m.media-amazon.com/images/I/81p-9S+eYwL._AC_UY218_.jpg",
    price: 90,
    discountPercent: 25,
    discountedPrice: 67.5,
    genres: ["Philosophy", "Adventure"],
    tags: ["Bestseller", "Classic"],
    rating: 4.8,
    reviews: 1100,
    stock: 8,
  },
  {
    id: 5,
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    image: "https://m.media-amazon.com/images/I/91lRx+XOCpL._AC_UY218_.jpg",
    price: 130,
    discountPercent: 20,
    discountedPrice: 104,
    genres: ["Finance", "Self-Help"],
    tags: ["Recommended", "Top Discounts"],
    rating: 4.6,
    reviews: 670,
    stock: 12,
  },
  {
    id: 6,
    title: "1984",
    author: "George Orwell",
    image: "https://m.media-amazon.com/images/I/91SzrhVa7CL._AC_UY218_.jpg",
    price: 110,
    discountPercent: 10,
    discountedPrice: 99,
    genres: ["Dystopian", "Political Fiction"],
    tags: ["Classic", "Trending"],
    rating: 4.9,
    reviews: 2000,
    stock: 3,
  },
  {
    id: 7,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    image: "https://m.media-amazon.com/images/I/81OxWCrVZgL._AC_UY218_.jpg",
    price: 140,
    discountPercent: 15,
    discountedPrice: 119,
    genres: ["Classic", "Drama"],
    tags: ["Recommended", "Bestseller"],
    rating: 4.8,
    reviews: 1200,
    stock: 9,
  },
  {
    id: 8,
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    image: "https://m.media-amazon.com/images/I/81T6h1xUcuL._AC_UY218_.jpg",
    price: 160,
    discountPercent: 30,
    discountedPrice: 112,
    genres: ["Self-Help", "Psychology"],
    tags: ["Top Discounts", "Trending"],
    rating: 4.5,
    reviews: 980,
    stock: 6,
  },
  {
    id: 9,
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    image: "https://m.media-amazon.com/images/I/81WWiiLgLtL._AC_UY218_.jpg",
    price: 180,
    discountPercent: 20,
    discountedPrice: 144,
    genres: ["History", "Anthropology"],
    tags: ["Recommended", "Bestseller"],
    rating: 4.9,
    reviews: 1150,
    stock: 4,
  },
  {
    id: 10,
    title: "Becoming",
    author: "Michelle Obama",
    image: "https://m.media-amazon.com/images/I/81h2gWPTYJL._AC_UY218_.jpg",
    price: 200,
    discountPercent: 25,
    discountedPrice: 150,
    genres: ["Biography", "Inspiration"],
    tags: ["Trending", "Bestseller"],
    rating: 4.7,
    reviews: 980,
    stock: 7,
  },
  {
    id: 11,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    image: "https://m.media-amazon.com/images/I/91WS6UK-72L._AC_UY218_.jpg",
    price: 95,
    discountPercent: 10,
    discountedPrice: 85.5,
    genres: ["Classic", "Drama"],
    tags: ["Classic", "Trending"],
    rating: 4.4,
    reviews: 900,
    stock: 5,
  },
  {
    id: 12,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    image: "https://m.media-amazon.com/images/I/81AFocWBFsL._AC_UY218_.jpg",
    price: 85,
    discountPercent: 15,
    discountedPrice: 72.25,
    genres: ["Classic", "Drama"],
    tags: ["Bestseller", "Recommended"],
    rating: 4.6,
    reviews: 890,
    stock: 10,
  },
  {
    id: 13,
    title: "The Power of Habit",
    author: "Charles Duhigg",
    image: "https://m.media-amazon.com/images/I/81Qwnp+WbFL._AC_UY218_.jpg",
    price: 170,
    discountPercent: 20,
    discountedPrice: 136,
    genres: ["Self-Help", "Psychology"],
    tags: ["Trending", "Recommended"],
    rating: 4.8,
    reviews: 780,
    stock: 8,
  },
  {
    id: 14,
    title: "Dune",
    author: "Frank Herbert",
    image: "https://m.media-amazon.com/images/I/91+N4hgAtvL._AC_UY218_.jpg",
    price: 190,
    discountPercent: 10,
    discountedPrice: 171,
    genres: ["Science Fiction", "Adventure"],
    tags: ["Bestseller", "Classic"],
    rating: 4.9,
    reviews: 1400,
    stock: 12,
  },
  {
    id: 15,
    title: "Think and Grow Rich",
    author: "Napoleon Hill",
    image: "https://m.media-amazon.com/images/I/91UFEoOa1wL._AC_UY218_.jpg",
    price: 150,
    discountPercent: 30,
    discountedPrice: 105,
    genres: ["Finance", "Self-Help"],
    tags: ["Top Discounts", "Trending"],
    rating: 4.7,
    reviews: 1120,
    stock: 7,
  },
  {
    id: 16,
    title: "Percy Jackson and the Olympians: The Lightning Thief",
    author: "Rick Riordan",
    image: "https://m.media-amazon.com/images/I/91bc+2HgguL._AC_UY218_.jpg",
    price: 95,
    discountPercent: 15,
    discountedPrice: 80.75,
    genres: ["Fantasy", "Adventure"],
    tags: ["Recommended", "For Kids"],
    rating: 4.8,
    reviews: 950,
    stock: 10,
  },
  {
    id: 17,
    title: "The Art of War",
    author: "Sun Tzu",
    image: "https://m.media-amazon.com/images/I/91jB8joE2ZL._AC_UY218_.jpg",
    price: 110,
    discountPercent: 20,
    discountedPrice: 88,
    genres: ["Philosophy", "Military Strategy"],
    tags: ["Classic", "Recommended"],
    rating: 4.7,
    reviews: 870,
    stock: 15,
  },
  {
    id: 18,
    title: "Goodnight Moon",
    author: "Margaret Wise Brown",
    image: "https://m.media-amazon.com/images/I/81rDWU8ecDL._AC_UY218_.jpg",
    price: 50,
    discountPercent: 10,
    discountedPrice: 45,
    genres: ["Children's Literature", "Bedtime Stories"],
    tags: ["For Kids", "Bestseller"],
    rating: 4.9,
    reviews: 700,
    stock: 20,
  },
  {
    id: 19,
    title: "Meditations",
    author: "Marcus Aurelius",
    image: "https://m.media-amazon.com/images/I/91TNiS54M4L._AC_UY218_.jpg",
    price: 130,
    discountPercent: 25,
    discountedPrice: 97.5,
    genres: ["Philosophy", "Classic"],
    tags: ["Bestseller", "Inspirational"],
    rating: 4.8,
    reviews: 780,
    stock: 6,
  },
  {
    id: 20,
    title: "Anne of Green Gables",
    author: "L.M. Montgomery",
    image: "https://m.media-amazon.com/images/I/81vPzlxNhXL._AC_UY218_.jpg",
    price: 85,
    discountPercent: 15,
    discountedPrice: 72.25,
    genres: ["Classic", "Children's Literature"],
    tags: ["For Kids", "Classic"],
    rating: 4.7,
    reviews: 880,
    stock: 12,
  },
  {
    id: 21,
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    image: "https://m.media-amazon.com/images/I/81J9RxEXemL._AC_UY218_.jpg",
    price: 200,
    discountPercent: 20,
    discountedPrice: 160,
    genres: ["Science", "Non-Fiction"],
    tags: ["Recommended", "Trending"],
    rating: 4.9,
    reviews: 1200,
    stock: 4,
  },
];
